#ifndef LIL_CURRENT_VERSION_INCLUDED
#define LIL_CURRENT_VERSION_INCLUDED

#define LIL_CURRENT_VERSION_VALUE 45
#define LIL_CURRENT_VERSION_MAJOR 1
#define LIL_CURRENT_VERSION_MINOR 9
#define LIL_CURRENT_VERSION_PATCH 0

#endif  // LIL_CURRENT_VERSION_INCLUDED
